spring.application.name=AUTH-SERVER

# ????
#kakao.client-id=${KAKAO_CLIENT_ID}
#kakao.redirect-uri=${KAKAO_REDIRECT_URI}
#kakao.client-id=95a754a05dd6038bbb636a608681308a
#kakao.redirect-uri=https://refresh-f5.store/auth/

#MySQL
#spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/auth-server?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=qwer1234

#AWS
spring.datasource.driver-class-name=${DB_NAME}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true


server.port=${SERVER_PORT}
eureka.instance.lease-renewal-interval-in-seconds=600
eureka.instance.lease-expiration-duration-in-seconds=630
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=43.200.249.25:8761
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=${IP_ADDRESS}

spring.security.oauth2.client.provider.keycloak.issuer-uri=${ISSUER_URI}
spring.security.oauth2.client.registration.keycloak.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.keycloak.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.redirect-uri=${REDIRECT_URI}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}

#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://13.124.171.192:8090/realms/test
#spring.security.oauth2.client.registration.keycloak.client-id=testClient
#spring.security.oauth2.client.registration.keycloak.client-secret=cKqNJl0AdmttMi5Fq4SOTCm6AmSz8dlX
#spring.security.oauth2.client.registration.keycloak.redirect-uri=http://13.124.171.192:8090/login/oauth2/code/testClient
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://13.124.171.192:8090/realms/test

management.endpoint.health.status.http-mapping.UP=200
management.endpoint.health.status.http-mapping.DOWN=503
management.endpoint.health.status.http-mapping.OUT_OF_SERVICE=503
management.endpoint.health.status.http-mapping.UNKNOWN=500
#
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/aws-springboot
#spring.security.oauth2.client.registration.keycloak.client-id=spring-security
#spring.security.oauth2.client.registration.keycloak.client-secret=HSKuu6NztHqKtrxPCbJHTnj22i6nhKQa
#spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8080/login/oauth2/code/spring-security
#

#spring.security.oauth2.client.registration.enabled=false
